# Permalinks
permalink:           pretty

# Setup
title:               "Horace Williams"
tagline:             kunderwammer
url:                 http://worace.works
paginate:            8
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Horace Williams
  url:               https://twitter.com/worace
  email:             horacedwilliams@gmail.com

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/worace/worace.github.io
# Templates for Rakefile generators:
post:
  template: _templates/_post.txt
  extension: org